### zip, stack 都不是我們要的轉法
https://stackoverflow.com/questions/44409084/how-to-zip-two-1d-numpy-array-to-2d-numpy-array

In [7]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [8]:
c = np.dstack((a,b))
print(c.shape)
c

(1, 5, 2)


array([[[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]]])

In [9]:
d = np.column_stack((a,b))
print(d.shape)
d

(5, 2)


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

### 其實用 transpose 就可以了
https://stackoverflow.com/questions/23943379/swapping-the-dimensions-of-a-numpy-array/23944468#23944468

In [14]:
exportFolder = "../00 dataset/"
with open(exportFolder+'train_price.npy', 'rb') as f:
    data = np.load(f)
data.shape

(88, 398, 3)

In [31]:
# (88, 398, 3) => (398, 88, 3)
# axis 0 1 2 => 1 0 2
res = np.transpose(data, (1, 0, 2))
res.shape

(398, 88, 3)

In [39]:
# APPL day 1 (2014-01-02): 
res[0, 0, :] == [0.064523, 0.067109, 0.057512]

array([ True,  True,  True])

In [44]:
# APPL day 2 (2014-01-03): 
print(res[1, 0, :])
res[1, 0, :] == [0.074229, 0.075861, 0.050077]

[0.074229 0.075861 0.050077]


array([False,  True, False])

In [45]:
# ABB day 1 (2014-01-02): 
res[0, 1, :] == [0.136685, 0.136685, 0.119746]

array([ True,  True,  True])

In [47]:
# ABB day 2 (2014-01-03): 
print(res[1, 1, :])
res[1, 1, :] == [0.161633, 0.166527, 0.158964]

[0.161633 0.166527 0.158964]


array([ True,  True, False])

### 那就開始轉所有data的dimension吧

In [48]:
exportFolder = "../00 dataset/"

In [49]:
price_npy_list = ['train_price.npy','valid_price.npy','test_price.npy']
for name in price_npy_list:
    with open(exportFolder+name, 'rb') as f:
        data = np.load(f)
        res = np.transpose(data, (1, 0, 2))
        print(res.shape)
        
    with open(exportFolder+name, 'wb') as f:
        np.save(f, res)

(398, 88, 3)
(42, 88, 3)
(64, 88, 3)


In [51]:
label_npy_list = ['train_label.npy','valid_label.npy','test_label.npy']
for name in label_npy_list:
    with open(exportFolder+name, 'rb') as f:
        data = np.load(f)
        res = np.transpose(data, (1, 0))
        print(res.shape)
        
#     with open(exportFolder+name, 'wb') as f:
#         np.save(f, res)

(398, 88)
(42, 88)
(64, 88)
